### ISSUE TITLE
mysqli::close(): Couldn't fetch mysqli

### ISSUE THREAD

**Issue by tvdsluijs** [joshcam/PHP-MySQLi-Database-Class#429]
When running on CLI I often get

PHP Warning:  mysqli::close(): Couldn't fetch mysqli in /public_html/vendor/joshcam/mysqli-database-class/MysqliDb.php on line 1504

But I do not close the connection myself. So it happens on destruct I guess. But why the error? Is the connection gone already? 

Maybe you should build in a connection check at that point.

**Comment by pieczarkazsolt** [comment]
I get same error, when I use copy() method (in ver2.5)

$db->where('T.delete', null, '<=>');
$dataQuery = $db->copy()
$sum = $db->getValue('test T', 'count(T.test_id)');
$testData = $dataQuery->withTotalCount()->where('T.date', null, '<=>')->get('test T', array($_POST['start'], $_POST['length']), 'T.test_id, T.test_desc);

In this case $testData is: PHP Warning: mysqli::close(): Couldn't fetch mysqli....
(same code works fine in ver2.2)

**Comment by DaGuich** [comment]
Do you run more than one instance of the class?

**Comment by tvdsluijs** [comment]
no. I dont

**Comment by joshghent** [comment]
@DaGuich I am also getting this error and have multiple instances of the class. Why would that affect things?

**Comment by joshghent** [comment]
@tvdsluijs @DaGuich Coming back to this now that I figured out the issue. For me it turned out to be that I was running multiple queries on the same class instance but the connection was being closed and then attempting to run a query.

The solution was to remove all the ->close() calls. My application still seems to be running fine. I know it's good practise to close the connection but maybe it should be removed from the library?

**Comment by avbdr** [comment]
> I know it's good practise to close the connection but maybe it should be removed from the library
Im not sure about the usecase you are having. 
mysql connection getting closed only on __destruct. Meaning when you destroying mysqlidb object. 

If you are doing close() after every sql query, this is no a best practices + this is slowing down your code. 
If you have a long running script, calling close() after sql query shouldnt cause any issues at least with latest mysqlidb version. Im using this for a long time and do not saw any problems

**Comment by joshghent** [comment]
@avbdr My use case was having multiple classes that use the MySqliDB class within them. The constructor for these classes take a mysqli object as an argument which is then passed to the mysqlidb. 

The constructors do not error but after the 3rd query I run it just fails to fetch the mysqli instance within the mysqlidb class. I googled around and came up with the issue of a connection being closed and then running a query on that closed connection (which would fail), sure enough, after I removed the ->close calls it worked fine.

Maybe there is more digging to be done here to solve this whether I'm at fault or there is something to fix in the library :)

**Comment by siberfx** [comment]
instead of using close(); in the end of each query, 
use this close on the footer part of the site, so when the page loads, it will close connection, each time you switch another page, in all the way you can set an init file to make the connection again. This is my advice, I am using it that way and no any problems and working fine.

**Comment by joshghent** [comment]
@siberfx The code I had wasn't closing the connection it was the mysqlidb library itself that was calling the close() method.

**Comment by avbdr** [comment]
fixed

**Comment by TeamOTLS** [comment]
thanks @joshghent  i will solve my problem now..
