### ISSUE TITLE
Protected with SQL injection ?

### ISSUE THREAD

**Issue by Wilou017** [joshcam/PHP-MySQLi-Database-Class#508]
is it protected against this for SQL injection like:
pass =
>' OR 1=1 or 1='

with

```
$db->where("email", $_POST["email"]);
$db->where("pass", $_POST["pass"]);
$user = $db->getOne("users");
```

**Comment by ricwein** [comment]
Since this *MySQLiDB* class uses php mysqli **prepared statements**, the resulting queries are protected against SQL injections - yes.

Read more about prepared statements here:
- (mysql prepared Statements)[https://dev.mysql.com/doc/refman/5.7/en/sql-syntax-prepared-statements.html]
- (php mysqli prepared statements)[https://secure.php.net/manual/en/mysqli.quickstart.prepared-statements.php]

**Comment by Jbithell** [comment]
+1

**Comment by Wilou017** [comment]
thanks @ricwein
