### ISSUE TITLE
Not compatable with PHP 5.3

### ISSUE THREAD

**Issue by burgoyn1** [joshcam/PHP-MySQLi-Database-Class#509]
On line 695, an empty array is declared using [] which is not supported in php 5.3.

**Comment by ricwein** [comment]
Fixed with MR #510, if merged.

But be aware, any php version earlier than 5.6 isn't [supported](https://secure.php.net/supported-versions.php) any longer, meaning no security patches are applied. If anyone is still using a version this old, it might be a good idea to upgrade to a newer release soon.

**Comment by burgoyn1** [comment]
Thanks. Yes, I know, in the process of upgrading it but in the meantime only works on 5.3
