### ISSUE TITLE
Other database types

### ISSUE THREAD

**Issue by Jbithell** [joshcam/PHP-MySQLi-Database-Class#620]
Are there any plans for this library to also support SQLite, MSSQL, etc. as I understand this library uses PDO?

**Comment by ricwein** [comment]
This library uses the **MySQLi** extension which is not able to connect to other databases than MySQL. Therefor no plans to port this library to other extensions exists (as far as I know!).

There was an issue for adapting the core to use PDO instead (as paid contract) some time ago... #471.

Also according to #356 a [PDO wrapper](https://github.com/tommyknocker/pdo-database-class) exists, but it's an old fork, with no maintenance since one year.

**Comment by abhishekpunj** [comment]
i modified this library, now i can switch from mysqli to pdo.

**Comment by abhishekpunj** [comment]
we modified this library now we can change mysqli to pdo just change on connection name.

**Comment by Dibbyo456** [comment]
There is wrapper called [Medoo](https://github.com/catfan/Medoo), which uses PDO and support almost every database including SQLite.
